Fix lang

diff --git a/run-emulator b/run-emulator
--- a/run-emulator
+++ b/run-emulator
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-/android/sdk/launch-emulator.sh > emulator.log 2>&1 &
+cd $ANDROID_HOME && $ANDROID_HOME/launch-emulator.sh > emulator.log 2>&1 &
 
 # Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain
 
@@ -12,16 +12,19 @@ timeout_in_sec=360
 
 until [[ "$bootanim" =~ "stopped" ]]; do
   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
+  let "failcounter += 1"
+
   if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
     || "$bootanim" =~ "running" ]]; then
-    let "failcounter += 1"
     echo "Waiting for emulator to start"
-    if [[ $failcounter -gt timeout_in_sec ]]; then
-      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-      exit 1
-    fi
   else
     echo "Out from adb: $bootanim"
+  fi
+
+  if [[ $failcounter -gt timeout_in_sec ]]; then
+    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+    cat emulator.log
+    exit 1
   fi
   sleep 1
 done
